# Generated by Django 5.2 on 2025-09-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0007_remove_emprestimo_multa_paga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa_por_dia', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
            ],
        ),
    ]
