# Generated by Django 5.2 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0009_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='funcao',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('bibliotecario', 'Bibliotecário')], default='bibliotecario', max_length=20),
        ),
    ]
