# Generated by Django 5.2 on 2025-10-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0010_perfilusuario_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='codigo_admin',
            field=models.CharField(default='10000', max_length=5),
        ),
    ]
