# Generated by Django 5.2.7 on 2026-03-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0011_configuracao_codigo_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='codigo_admin',
        ),
    ]
